--------------------------------------------------------
--  File created - Monday-November-25-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "TAIMOOR"."ADMIN" 
   (	"ECUSERNAME" VARCHAR2(100 BYTE), 
	"ECPASSWORD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUYER
--------------------------------------------------------

  CREATE TABLE "TAIMOOR"."BUYER" 
   (	"ECUSERNAME" VARCHAR2(100 BYTE), 
	"ECPASSWORD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHECKOUT
--------------------------------------------------------

  CREATE TABLE "TAIMOOR"."CHECKOUT" 
   (	"CHECKOUTNO" NUMBER(*,0), 
	"PURCHASETIME" TIMESTAMP (6), 
	"PURCHASEITEM" NUMBER(*,0), 
	"CUSTOMER" VARCHAR2(100 BYTE), 
	"COUPONAPPLIED" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COUPON
--------------------------------------------------------

  CREATE TABLE "TAIMOOR"."COUPON" 
   (	"DISCOUNTNAME" VARCHAR2(100 BYTE), 
	"DOLLARVALUE" NUMBER(*,0), 
	"OFSTORE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "TAIMOOR"."PRODUCT" 
   (	"PRODUCTID" NUMBER(*,0), 
	"PRODUCTNAME" VARCHAR2(100 BYTE), 
	"PRODUCTPRICE" NUMBER(*,0), 
	"OFSTORE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "TAIMOOR"."REVIEW" 
   (	"REVIEWID" NUMBER(*,0), 
	"RATING" NUMBER(*,0), 
	"REVIEWTEXT" NUMBER(*,0), 
	"REVIEWPRODUCT" NUMBER(*,0), 
	"REVIEWBUYER" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SELLER
--------------------------------------------------------

  CREATE TABLE "TAIMOOR"."SELLER" 
   (	"ECUSERNAME" VARCHAR2(100 BYTE), 
	"ECPASSWORD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOREFRONT
--------------------------------------------------------

  CREATE TABLE "TAIMOOR"."STOREFRONT" 
   (	"STORENAME" VARCHAR2(100 BYTE), 
	"STOREOWNER" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View CHEAP_PRODUCTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TAIMOOR"."CHEAP_PRODUCTS" ("PRODUCTID", "PRODUCTNAME", "PRODUCTPRICE", "OFSTORE") AS 
  select "PRODUCTID","PRODUCTNAME","PRODUCTPRICE","OFSTORE" from product where ofstore = 'BrandonMart' and productprice <= 50
;
--------------------------------------------------------
--  DDL for View DEALS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TAIMOOR"."DEALS" ("PRODUCTID", "PRODUCTNAME", "PRODUCTPRICE", "OFSTORE") AS 
  select "PRODUCTID","PRODUCTNAME","PRODUCTPRICE","OFSTORE" from product where productprice <= 50
;
--------------------------------------------------------
--  DDL for View LATEST_PURCHASES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TAIMOOR"."LATEST_PURCHASES" ("CHECKOUTNO", "PURCHASETIME", "PURCHASEITEM", "CUSTOMER", "COUPONAPPLIED") AS 
  select "CHECKOUTNO","PURCHASETIME","PURCHASEITEM","CUSTOMER","COUPONAPPLIED" from checkout order by purchasetime desc
;
REM INSERTING into TAIMOOR.ADMIN
SET DEFINE OFF;
Insert into TAIMOOR.ADMIN (ECUSERNAME,ECPASSWORD) values ('taimoor','password');
REM INSERTING into TAIMOOR.BUYER
SET DEFINE OFF;
Insert into TAIMOOR.BUYER (ECUSERNAME,ECPASSWORD) values ('jeff','password');
REM INSERTING into TAIMOOR.CHECKOUT
SET DEFINE OFF;
Insert into TAIMOOR.CHECKOUT (CHECKOUTNO,PURCHASETIME,PURCHASEITEM,CUSTOMER,COUPONAPPLIED) values (1,to_timestamp('09-OCT-19 08.32.23.948000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1,'jeff',null);
Insert into TAIMOOR.CHECKOUT (CHECKOUTNO,PURCHASETIME,PURCHASEITEM,CUSTOMER,COUPONAPPLIED) values (2,to_timestamp('09-OCT-19 08.33.15.844000000 AM','DD-MON-RR HH.MI.SSXFF AM'),2,'jeff','5OFF');
REM INSERTING into TAIMOOR.COUPON
SET DEFINE OFF;
Insert into TAIMOOR.COUPON (DISCOUNTNAME,DOLLARVALUE,OFSTORE) values ('5OFF',5,'BrandonMart');
REM INSERTING into TAIMOOR.PRODUCT
SET DEFINE OFF;
Insert into TAIMOOR.PRODUCT (PRODUCTID,PRODUCTNAME,PRODUCTPRICE,OFSTORE) values (1,'Headphones',99,'BrandonMart');
Insert into TAIMOOR.PRODUCT (PRODUCTID,PRODUCTNAME,PRODUCTPRICE,OFSTORE) values (2,'Wireless mouse',29,'BrandonMart');
REM INSERTING into TAIMOOR.REVIEW
SET DEFINE OFF;
REM INSERTING into TAIMOOR.SELLER
SET DEFINE OFF;
Insert into TAIMOOR.SELLER (ECUSERNAME,ECPASSWORD) values ('brandon','password');
REM INSERTING into TAIMOOR.STOREFRONT
SET DEFINE OFF;
Insert into TAIMOOR.STOREFRONT (STORENAME,STOREOWNER) values ('BrandonMart','brandon');
--------------------------------------------------------
--  Constraints for Table CHECKOUT
--------------------------------------------------------

  ALTER TABLE "TAIMOOR"."CHECKOUT" ADD PRIMARY KEY ("CHECKOUTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAIMOOR"."CHECKOUT" MODIFY ("CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."CHECKOUT" MODIFY ("PURCHASEITEM" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."CHECKOUT" MODIFY ("PURCHASETIME" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."CHECKOUT" MODIFY ("CHECKOUTNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUYER
--------------------------------------------------------

  ALTER TABLE "TAIMOOR"."BUYER" ADD PRIMARY KEY ("ECUSERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAIMOOR"."BUYER" MODIFY ("ECPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."BUYER" MODIFY ("ECUSERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "TAIMOOR"."ADMIN" ADD PRIMARY KEY ("ECUSERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAIMOOR"."ADMIN" MODIFY ("ECPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."ADMIN" MODIFY ("ECUSERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SELLER
--------------------------------------------------------

  ALTER TABLE "TAIMOOR"."SELLER" ADD PRIMARY KEY ("ECUSERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAIMOOR"."SELLER" MODIFY ("ECPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."SELLER" MODIFY ("ECUSERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "TAIMOOR"."REVIEW" ADD PRIMARY KEY ("REVIEWID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAIMOOR"."REVIEW" MODIFY ("REVIEWBUYER" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."REVIEW" MODIFY ("REVIEWPRODUCT" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."REVIEW" MODIFY ("REVIEWTEXT" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."REVIEW" MODIFY ("RATING" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."REVIEW" MODIFY ("REVIEWID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STOREFRONT
--------------------------------------------------------

  ALTER TABLE "TAIMOOR"."STOREFRONT" ADD PRIMARY KEY ("STORENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAIMOOR"."STOREFRONT" MODIFY ("STOREOWNER" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."STOREFRONT" MODIFY ("STORENAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "TAIMOOR"."PRODUCT" ADD PRIMARY KEY ("PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAIMOOR"."PRODUCT" MODIFY ("OFSTORE" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."PRODUCT" MODIFY ("PRODUCTPRICE" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."PRODUCT" MODIFY ("PRODUCTNAME" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."PRODUCT" MODIFY ("PRODUCTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COUPON
--------------------------------------------------------

  ALTER TABLE "TAIMOOR"."COUPON" ADD PRIMARY KEY ("DISCOUNTNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAIMOOR"."COUPON" MODIFY ("OFSTORE" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."COUPON" MODIFY ("DOLLARVALUE" NOT NULL ENABLE);
  ALTER TABLE "TAIMOOR"."COUPON" MODIFY ("DISCOUNTNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CHECKOUT
--------------------------------------------------------

  ALTER TABLE "TAIMOOR"."CHECKOUT" ADD FOREIGN KEY ("PURCHASEITEM")
	  REFERENCES "TAIMOOR"."PRODUCT" ("PRODUCTID") ENABLE;
  ALTER TABLE "TAIMOOR"."CHECKOUT" ADD FOREIGN KEY ("CUSTOMER")
	  REFERENCES "TAIMOOR"."BUYER" ("ECUSERNAME") ENABLE;
  ALTER TABLE "TAIMOOR"."CHECKOUT" ADD FOREIGN KEY ("COUPONAPPLIED")
	  REFERENCES "TAIMOOR"."COUPON" ("DISCOUNTNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COUPON
--------------------------------------------------------

  ALTER TABLE "TAIMOOR"."COUPON" ADD FOREIGN KEY ("OFSTORE")
	  REFERENCES "TAIMOOR"."STOREFRONT" ("STORENAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "TAIMOOR"."PRODUCT" ADD FOREIGN KEY ("OFSTORE")
	  REFERENCES "TAIMOOR"."STOREFRONT" ("STORENAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "TAIMOOR"."REVIEW" ADD FOREIGN KEY ("REVIEWPRODUCT")
	  REFERENCES "TAIMOOR"."PRODUCT" ("PRODUCTID") ENABLE;
  ALTER TABLE "TAIMOOR"."REVIEW" ADD FOREIGN KEY ("REVIEWBUYER")
	  REFERENCES "TAIMOOR"."BUYER" ("ECUSERNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STOREFRONT
--------------------------------------------------------

  ALTER TABLE "TAIMOOR"."STOREFRONT" ADD FOREIGN KEY ("STOREOWNER")
	  REFERENCES "TAIMOOR"."SELLER" ("ECUSERNAME") ENABLE;
